version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_HOST=sharmen.store
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://sharmen.store/
    volumes:
      - ~/.n8n:/home/node/.n8n
